### ISSUE TITLE
Windows code signing certificate

### ISSUE THREAD

**Issue by feinstaub** [feinstaub/webextension_local_filesystem_links#100]
I like to bundle all discussion about buying a Windows code signing certificate here.

See also
* screenshot the warning message box: https://github.com/feinstaub/webextension_local_filesystem_links/issues/95#issuecomment-347049763
* comment on "Windows Code signing" here: https://github.com/feinstaub/webextension_local_filesystem_links/issues/81#issuecomment-350543266
* comment on money here: https://github.com/feinstaub/webextension_local_filesystem_links/pull/99#issuecomment-355812525

Next question: What are possible vendors who sell such certificates and how much do they charge? Is this a one-time payment or do we expect to pay more in the future?

**Comment by feinstaub** [comment]
see also: https://github.com/feinstaub/webextension_local_filesystem_links/pull/99#issuecomment-355814206

> Good that you have created a issue for this. Thanks. I'll add a animated give there that's showing the dialog - to see initial dialog and after clicking show more.

> Should we add an info to installed.html about this? We can also add the image there. I think that would help.

I also think that adding information about this is a good idea.

**Comment by feinstaub** [comment]
I am still pondering if which case the code signing makes sense.

1) If we would be the attackers, the signing would not help the user.
2) Could some attacker replace our binary with his one?
a) If yes and his code is not signed, there would be a warning message => Good.
b) What would happen if the attacker also has signed his code?

**Comment by AWolf81** [comment]
Nice read at Stackoverflow [here](https://stackoverflow.com/questions/1732927/signed-executables-under-linux). One answer is really interesting and why he stopped using code signing in Linux. e.g. what happens if a library or bash is modified.

So the certificate can only tell the user that the software wasn't modified after signing and that it is from the author that signed the file. 
But if a user downloads a signed malicious file with the same name but different signing it won't prevent the execution.

Signing benefits are small - so I would do the signing only if it's not that expensive.

I've found one CA site that has an acceptable price 86€ net (1st year) and 28€ the following years. 

I'd like to list the CA sites for open source here (so we're having an overview):
- [certum.pl](https://en.sklep.certum.pl/data-safety/code-signing-certificates/open-source-code-signing-935.html) 86€ net 1st year / 28€ net following years - [here](http://www.anse.de/programming/code-signing-for-open-source-executable) is a blog post guide for usage
- <del>[Thawte](https://www.thawte.de/code-signing/) too expensive - 270€ per year</del>
- <del>[Comodo](https://www.comodo.com/business-security/code-signing-certificates/code-signing.php) too expensive - 180€ per year</del>
- [Leaderssl re-selling Comodo](https://www.leaderssl.de/suppliers/comodo/products/code_signing?keyword=Code%20signing&gclid=EAIaIQobChMIvoqpjofG2AIVCLftCh1xjA-OEAAYAiAAEgKlSPD_BwE) 63€ per year - acceptable but still more expensive then Certum

**Comment by AWolf81** [comment]
Thanks for the donations - @PeterZamudio @therouv and the other donators that I haven't mentioned.
The donated ammount is close to the value that I had to pay for the certificate (the rest is from me ~24 €)

I've ordered the certificate at Certum.pl for €135.78 on 10th January and now I have to wait for the code signing hardware to arrive.

Once it arrived I'll sign the executables (installer & app) for windows and push it to the binaries repo.

**Comment by AWolf81** [comment]
**Update to the certificate:**
The certificate is currently in verification and I think it should be ready early next week. 

I received the signing hardware two days ago but I had some troubles with installing it. But yesterday installation worked after updating Java.

There is still something unclear as there are two PUK/PINs (securtiy profile & common profile) and I need to get the second one. But I think I'll get the PUK from Certum after verification of the certificate. The first PUK & PIN in common profile could be created by myself.

**Comment by feinstaub** [comment]
I am curious, what's the purpose of the signing hardware? Does it come with ordering the certificate or is it something you had to order separately?

**Comment by AWolf81** [comment]
It's coming with the certificate order and I think it's used to store the certificate and as two-factor authentication (first auth. is the PIN entry).

The hardware is a USB stick and installs as smart card reader. More to read about it [here](https://www.certum.eu/certum/cert,offer_smart_cards_and_readers.xml).

**Comment by AWolf81** [comment]
OK, I released a signed installer for Windows with version 0.2.2.

But the Windows Defender message is still showing the warning. With just a small difference that now my name is displayed in that message.

I'll check if there is something like a reputation that's stored in Windows cloud. I've read about that [here](https://social.technet.microsoft.com/Forums/de-DE/38df89b4-68c0-41ac-8c37-884a7de8a019/smartscreenfehlermeldung-auch-bei-signierten-exe-files?forum=tnofftopicde) and [here](https://trustedwindows.wordpress.com/hauptseite/trusted-computing-in-windows/smartscreen-app-reputation/).

**Comment by AWolf81** [comment]
Today, I've tested the installer again and now it's working with-out warning. 

So we can close this issue now.
