### ISSUE TITLE
Silent installation of Native App

### ISSUE THREAD

**Issue by lhw-sa** [feinstaub/webextension_local_filesystem_links#105]
Hey,
we deploy Firefox ESR and the local filesystem link addon in our company. Now I have to deploy the native app setup, too. I found silent installation options in “native-app-setup.exe /?”. The switch “/VERYSILENT” works, but brings up an error, that a file can not be found, I guess it’s the c++-redistributable setup. The addon works, even without c++-redistributable installation. But an error window during a silent installation is bad, the user must click in the error window.
Second problem, is that all files are installed in “C:\Users\<user>\Local_file_links-Native_API_Host” and not in “c:\programm files”. I can not install the application for every user on the system, only for the whole system. How to install this app system wide?

Torsten

**Comment by AWolf81** [comment]
Thanks for the details to your deployment.

At the moment the installer is on a per-user basis and installs the native app into the user's home directory as you've mentioned. I decided to do it like this to enable the user to install the app with-out admin rights. The admin rights are only required if the C++ redistributable is missing at the target system - for most system that dependency is already available.
Program folder location also requires admin rights because that folder is usually locked for standard users that's why it's in user's home directory.

The thing with the missing file I need to check why this is happening.

I think it's possible to add an option to the installer to decide to install it globally but I need to check how to do it. This will require admin rights but that's probaly OK for a system wide installation.

**Points I need to check:**
- [ ] Modify native host app location in manifest json during installation or use two manifest files? Two locations user home or `C:\Program files\Local link extension host app\...` 
- [ ] How to add an installer option to decide between `per user` or `system-wide` installation? Check InnoSetup docs.
- [ ] Is this option automatically available during silent installation?
- [ ] What the problem with the missing file?

**A work-around (not tested yet)** until I've fixed the installer could be:
1. Install the native app on your development machine with the per-user installer.
2. Modify the path key inside `manifest.json` in `C:\Users\<user>\Local_file_links-Native_API_Host` to `"path": "C:\\Program Files\\Local link extension host app\\local-link-messaging-host.exe",` with a text editor and save it.
3. Copy the contents of the home directory location to the new location in program folder path as written in the manifest.
4. Add a key to the registry Subkey `HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\NativeMessagingHosts\webextension_local_filesystem_links` valueType String, valueName ""
5. Uninstall the installed files of the per user installer.
6. Test the extension on your machine. It should be now available for all local users.
7. 1 to 6 only needed to test if it is working. Deploy the program folder to each machine by copying and add the key in registry. That's possible with a batch file with admin rights. For an example batch for adding a registry key you can have a look [here](https://github.com/feinstaub/webextension_local_filesystem_links/blob/master/native-host/src/install_host.bat).

I know the work-around is a bit complicated but it should work. I'll test the work-around later today. I'm not sure how fast I can fix the installer. Maybe I can have a look at it at the weekend but I can not promise.

**Comment by lhw-sa** [comment]
I tried your work-around, and it works, even with our deployment tool. I tested it on windows 7 pro and windows 10 enterprise clients. Installation of c++ redistributable was not necessary.
The manifest file is called “webextension_local_filesystem_links_win.json” and I moved the directory to c:\Program Files (x86) , because I use the 32 bit version of firefox.
With this kind of “installation” I avoid the error window, too.
Thanks, but a complete installation package is still better.
Torsten

**Comment by AWolf81** [comment]
@lhw-sa OK, the next version 0.2.2 will be with an installer that can run silently.

The installer will automatically detect that it runs silently and also checks that the rights are elevated (admin rights required). Then it will install the registry key to HKLM and the files to program folders (at my machine to `c:\Programme (x86)\Local file links Native Messaging API Host`)

I've added a selection page (see below) to the installer so the user can pick if the app is installed for current user only or system-wide. System-wide requires administrator rights.

![Installation type](https://user-images.githubusercontent.com/3046542/36344994-32d74184-1423-11e8-9354-5c5805cbbb6b.png)

I wanted to add automatic elevation of permissions but couldn't find a way to fix it. So for normal user it will just show a message that elevated rights are required to install for all users and a manual restart would be required. I think that's OK for now.

![info message](https://user-images.githubusercontent.com/3046542/36345004-84026d40-1423-11e8-8117-2e010027ac94.png)

One point that could be improved is that if the installer is started with runAs administrator and then it's only installed for current user it will add the registry key to HKLM with the path pointing to admin's user directory and other users can also use the native app. The app is working it's just not installed as expected.
I'll keep it for now as the programmatic registry key generation in InnoSetup is not that easy to program.
 
So I think your deployment should work with the new installer. I've tested the installer on Win10 Pro and it's working for all my user accounts. 

The issue with C++ redistributable is also fixed. So no error messages anymore.

I'll add a comment here once I've pushed the new installer. 
I'm delaying it a bit because I'd like to check if I can also sign the installer.

**Comment by AWolf81** [comment]
@lhw-sa OK, I released the new installer.

Silent installation not tested again but I've tested the system wide installation.

So I think I can close this issue. If there is still something not working with the installer please let me know and I'll fix it.
