### ISSUE TITLE
Multiple windows opened

### ISSUE THREAD

**Issue by alexander-toth** [feinstaub/webextension_local_filesystem_links#113]
Hello,
I'm testing your extension in several computers and I noticed this issue:
When I open a page the first time the extension works correctly and every folder link opens one window. But if I click on any other hyperlink (standard web page hyperlink, not file or folder link), then when I click again on a folder link this will open two windows. If I click again on a standard hyperlink, then the opened windows are 3, then 4, 5, 6, ...
You can also try this on your jsfiddle page, click on C folder (open 1 window), then click on google.de, then click again on C folder (open 2 windows), then click google.de, then C folder (open 3 windows), ...
I hope this can be useful for you, thanks!
Alexander

**Comment by AWolf81** [comment]
Thanks for reporting.

I've fixed that issue - it will be available in the next extension version. It was adding the scripts to the same tab again because I have missed to add a check.

It happened because the new tab wasn't active during loading (right click, load in new tab for non-file link) and it removed the tab index of the current tab (which shouldn't be removed) from the injection array that keeps track of tabs with content scripts. It then added the click handler multiple times.

**Comment by AWolf81** [comment]
OK, I think we can close this. It's improved in the new version 0.99.59.

If it still happens please let me know and add a comment here.
