### ISSUE TITLE
Installer error

### ISSUE THREAD

**Issue by snugga** [feinstaub/webextension_local_filesystem_links#121]
Trying to update to .57 to use with ProWorkFlow.

If I run the installer without ticking the box for "Install Visual C++ Re-distribute" the installer runs seemingly successfully, however when I restart Firefox and test it, the add on isn't working.

So next I tried ticking the box for "Install Visual C++ Re-distribute",
however when I click ''install'' a notification window comes up with:

"Other installed failed to run!
The system cannot find the file specified."

I've downloaded Install Visual C++ Re-distribute 2017 directly from the Microsoft site, LFL still isn't working. (I tried both the x64 and x86)

**Comment by AWolf81** [comment]
I've published a new version of the installer where the VC re-distributable installation is working.

Sorry, I had a mistake in the installation script.

Version 2017 is probably not working because the executable requires VC++ 2008 (version 9.0.21022.08) - same version that PyInstaller used.

Please try the new installer.
