### ISSUE TITLE
Release 0.99.59

### ISSUE THREAD

**Issue by feinstaub** [feinstaub/webextension_local_filesystem_links#122]
Validation report: https://addons.mozilla.org/en-US/developers/upload/82206d6f1188421a824cbaec6c9a144f

**Comment by feinstaub** [comment]
I had to change the version number 0.99.59.

**Comment by feinstaub** [comment]
New version is online.

**Comment by feinstaub** [comment]
I used this from the README.dev.md for local testing:

```
## Manually starting
Run `npm run dev`, open Firefox and enter about:debugging in url bar and load `dist\manifest.json` Extension.
```
Things I noticed:

* The http://jsfiddle.net/awolf2904/tefcs74q/ from the welcome page does not contain suitable links for testing under Linux.
* I downloaded the native-app-bundle-linux.tar, extracted it and ran:
```
./install_host_compiled.sh 
Native messaging host webextension_local_filesystem_links has been installed.
```
The clicking on a link does not work, though.

* http://jsfiddle.net/awolf2904/tefcs74q/: Context menu test: the context menu does not contain any item related to Local Filesystem Links
* native-app-bundle-linux.tar: Maybe this can be renamed to something more specific like "local_filesystem_links-native-app-linux"

**Comment by AWolf81** [comment]
Thanks for publishing the new version.

OK, I have to update the jsfiddle to also add some test links for Linux.
I've detected the behavior you've mentioned in OpenSuse as well. I have to check why the links are not opened. I tested the extension with Ubuntu and it works as expected.

I just need to change from VMware to a LiveUSB stick because my OpenSuse VM is very slow at the moment. So I can not debug the issue at the moment.

Renaming is no problem. I'll check this when I'm doing the next change for Linux.

Context menu features are still not implemented. That's something for a future version but I'm first fixing the bugs and improve the core features.

At the moment, I'm working on the Windows installer so it's possible to install the native app system-wide as some users need that. That's almost ready and I just need to do more tests.

**Comment by AWolf81** [comment]
@feinstaub I think we can close this issue.

I've fixed the issue with the installation in OpenSUSE. Seems like the binaries must be build for OpenSUSE - so I've uploaded a new tar-archive for OpenSUSE.

Renamig not done yet. I've missed that. I'll do it with the next version. I created an [issue](https://github.com/AWolf81/webextension_local_filesystem_links-native-host-binaries/issues/1) at the binaries repo for the renaming - so I have a reminder.
