### ISSUE TITLE
Add donation to Readme.md

### ISSUE THREAD

**Issue by AWolf81** [feinstaub/webextension_local_filesystem_links#98]
As requested in #95 it would be good to have a place to give users of the extensions the possibility to donate.

@feinstaub What do you think? Can we add donation links to [paypal.me](https://paypal.me) into the `readme.md`?
We could also add the links into the "Thanks for installing" page. That's similar to how I've first heard about Open collective - it was in the post install message of [nodemon](https://github.com/remy/nodemon#backers).

I've googled about the topic a bit and checked what other Open source projects are doing and I think a good example is Vue.js.

They're having multiple channels for donations. Please have a look [here](https://vuejs.org/support-vuejs/#One-time-Donations).

They're also using [Open collective](https://opencollective.com/vuejs) and [Patreon](https://www.patreon.com/evanyou).

I think the easiest way is to add the paypal.me link but I really like the concept of Open Collective. But it's probably a bit too complicated for the extension.

Patreon is not really an option for me as this is just a side project.

Additionally we could add a link to [Mozilla donation page](https://donate.mozilla.org/de/).

**Comment by feinstaub** [comment]
Hi @AWolf81,
thanks for the extensive research.

My thoughts:

* Many organisations use Paypal as one (or preferred) method for receiving donations. E.g. https://www.kde.org/community/donations/others.php or https://www.fsf.org/about/ways-to-donate/
* Generally, I think it is good to have not only Paypal as way of payment (see e.g. https://www.fsf.org/about/ways-to-donate/ for many options) since there is also critics https://de.wikipedia.org/wiki/PayPal#Kritik
* Since for you it is the easiest way to get money by Paypal, it is ok for me if you add your Paypal link to the README.md. Ideally, there should be a hint who (awolf81) is receiving the money and for what it is intended to be used: 1) buy a Windows code signing certificate, 2) what happens with the surplus money? -> personal compensation/incentive? donation to other organizations?
  * What do you think about also reporting back how much money in total was received?
* I agree that is good to add some other possibilities to donate money that benefit the addon, if only indirectly:
  * https://donate.mozilla.org/de/
  * https://www.kde.org/community/donations/others.php
  * https://www.fsf.org/about/ways-to-donate/
* If this is done, I will add some text about why I personally don't have a Paypal link or other donation channel yet: I currently do not expect much reliable income over this channel; I will spend my time for the addon anyway (or stop doing it someday); for me, it is a better to know that people donate the money to a charitable organization (education of the public of environmental issues, human rights issues, moral values and ethics in a global world, human treatment of animals (especially the current situation of animals used as "lifestock") or use their time for personal social commitment.

**Comment by MrWillow** [comment]
Since this add-on is such a life-saver in our corporate environment, I asked my manager to make a donation to FSF as a token of appreciation.
We don't (want to) use paypal over here.
And again: thank you for the upgrade to webextensions!

**Comment by AWolf81** [comment]
You're welcome and thanks for considering a donation.

I think it's also good to support open source software with the mentioned links above and it's OK to not use Paypal.

Good to hear that the extension is a big help for you. There is still some work to do to bring the extension back to the same level as it was before FF 57. But I think the core features are working again.

If you're having any issues please let us know.

**Comment by feinstaub** [comment]
Any donation that supports the Free Software community helps to maintain an environment where the development of addons like this are possible. For starters, I recommend these:

* https://www.kde.org/community/donations/others.php (now also supports Bitpay: https://bitpay.com/990273/donate)
* https://www.fsf.org/about/ways-to-donate/
* Software Freedom Conservancy: https://sfconservancy.org/donate/
* https://donate.mozilla.org/de/

**Comment by feinstaub** [comment]
@AWolf81: on the "Show install info..." page we should also link to the Donation section of the README (currently only the paypal link is presented)

**Comment by feinstaub** [comment]
@AWolf81 readme on donations is updated.

**Comment by AWolf81** [comment]
@feinstaub Thanks for updating. I like it.

**Comment by AWolf81** [comment]
I'll close this. Because the README is updated and contains the information.
